package cn.noname.app.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.noname.app.model.DownloadGame;

import cn.noname.app.db.DownloadGameDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadGameDaoConfig;

    private final DownloadGameDao downloadGameDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadGameDaoConfig = daoConfigMap.get(DownloadGameDao.class).clone();
        downloadGameDaoConfig.initIdentityScope(type);

        downloadGameDao = new DownloadGameDao(downloadGameDaoConfig, this);

        registerDao(DownloadGame.class, downloadGameDao);
    }
    
    public void clear() {
        downloadGameDaoConfig.clearIdentityScope();
    }

    public DownloadGameDao getDownloadGameDao() {
        return downloadGameDao;
    }

}
